/**
 * Phase 3: AI call insights worker (cron every 5 min).
 * Runs AI on transcript + context; stores ai_call_insights; generates follow-up drafts.
 * Emits event call_insights_ready. MVP: stub that writes placeholder insights.
 */

import { createClient } from 'npm:@supabase/supabase-js@2';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

Deno.serve(async (req: Request) => {
  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
  const now = new Date().toISOString();

  const { data: calls } = await supabase
    .from('calls')
    .select('id, user_id')
    .not('transcript_ref', 'is', null)
    .limit(30);

  let processed = 0;
  for (const call of calls ?? []) {
    const { data: insight } = await supabase
      .from('ai_call_insights')
      .select('call_id')
      .eq('call_id', call.id)
      .maybeSingle();
    if (insight) continue;

    const { data: transcript } = await supabase
      .from('call_transcripts')
      .select('transcript_text')
      .eq('call_id', call.id)
      .limit(1)
      .maybeSingle();

    const text = (transcript as { transcript_text?: string } | null)?.transcript_text ?? '';

    await supabase.from('ai_call_insights').insert({
      call_id: call.id,
      user_id: call.user_id,
      summary: text ? 'Summary not yet generated by Luma AI.' : null,
      action_items: [],
      objections: [],
      drafts: [
        { channel: 'email', subject: 'Follow-up', body: 'Thanks for the call. As discussed, next steps are…' },
        { channel: 'sms', body: 'Thanks for the call. I’ll follow up with the details we discussed.' },
      ],
      updated_at: now,
    });
    await supabase.from('messaging_events').insert({
      user_id: call.user_id,
      type: 'call_insights_ready',
      payload: { call_id: call.id },
    });
    processed++;
  }

  return new Response(
    JSON.stringify({ processed }),
    { headers: { 'Content-Type': 'application/json' } }
  );
});
