export interface ColorDefinition {
  name: string;
  value: string;
}

export const COLOR_SWATCHES: ColorDefinition[] = [
  { name: 'Snow', value: '#F9FAFB' },
  { name: 'Pearl', value: '#F3F4F6' },
  { name: 'Mist', value: '#E5E7EB' },
  { name: 'Silver Fog', value: '#D1D5DB' },
  { name: 'Ice Blue', value: '#E8F1FF' },
  { name: 'Cloud Blue', value: '#D6E7FF' },
  { name: 'Sky Wash', value: '#C3DBFF' },
  { name: 'Pale Azure', value: '#AECFFF' },
  { name: 'Soft Blue', value: '#98C3FF' },
  { name: 'Bluebell', value: '#87B6F9' },
  { name: 'Foggy Indigo', value: '#AEB8D9' },
  { name: 'Lavender Mist', value: '#F2EDFF' },
  { name: 'Lilac Whisper', value: '#E8E2FF' },
  { name: 'Soft Violet', value: '#D8D0FF' },
  { name: 'Periwinkle Light', value: '#C7C3FF' },
  { name: 'Muted Orchid', value: '#B7B2F2' },
  { name: 'Barely Purple', value: '#DDD6F6' },
  { name: 'Blush Tint', value: '#FFE8F3' },
  { name: 'Pink Dew', value: '#FFD6E8' },
  { name: 'Rosewater', value: '#F9C8DB' },
  { name: 'Petal Pink', value: '#F5B8CD' },
  { name: 'Soft Berry', value: '#E8A7C3' },
  { name: 'Muted Magenta', value: '#D3A6C9' },
  { name: 'Rose Mist', value: '#FFE5E5' },
  { name: 'Pale Coral', value: '#FFD4D4' },
  { name: 'Soft Clay', value: '#F5B8B8' },
  { name: 'Muted Red', value: '#EFA9A9' },
  { name: 'Peach Wash', value: '#FFF1E6' },
  { name: 'Apricot Mist', value: '#FFE3CC' },
  { name: 'Soft Tangerine', value: '#FFD1AE' },
  { name: 'Warm Peach', value: '#F7C39C' },
  { name: 'Muted Orange', value: '#E7B690' },
  { name: 'Sunhaze', value: '#FFF8DD' },
  { name: 'Lemon Tint', value: '#FFF2BB' },
  { name: 'Buttercream', value: '#FFECA1' },
  { name: 'Golden Mist', value: '#FFE38C' },
  { name: 'Muted Amber', value: '#F6D67C' },
  { name: 'Mint Wash', value: '#E6FFF5' },
  { name: 'Soft Mint', value: '#CFF9EA' },
  { name: 'Pale Green', value: '#B7F0D9' },
  { name: 'Seafoam', value: '#A1E8CC' },
  { name: 'Soft Teal', value: '#8EDCC0' },
  { name: 'Muted Green', value: '#7BCDB1' },
  { name: 'Aqua Mist', value: '#E5FAFF' },
  { name: 'Arctic Blue', value: '#CDF2FA' },
  { name: 'Icy Teal', value: '#B5E8F0' },
  { name: 'Soft Cyan', value: '#A1DEEA' },
  { name: 'Muted Teal', value: '#8DCFD9' },
  { name: 'Sandstone', value: '#F7EFE6' },
  { name: 'Driftwood', value: '#EADFD2' },
  { name: 'Clay Neutral', value: '#DDCEBF' },
  { name: 'Soft Taupe', value: '#CFC1B2' }
];

// Default to "Cloud Blue" - a soft, professional blue that works well for pipeline stages
export const DEFAULT_STATUS_COLOR = '#D6E7FF';
